# Generated by Django 3.0.6 on 2020-05-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='api_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
            ],
        ),
    ]
